INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (1, '上海', 'SHANGHAI');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (2, '宁波', 'NINGBO');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (3, '深圳', 'SHENZHEN');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (4, '温州', 'WENZHOU');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (5, '厦门', 'XIAMEN');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (6, '湛江', 'ZHANJIANG');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (7, '大连', 'DALIAN');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (8, '青岛', 'QINGDAO');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (9, '天津', 'TIANJIN');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (10, '汕头', 'SHANTOU');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (11, '张家港', 'ZHANGJIAGANG');
INSERT INTO TB_CHINAPORT (FID, FPORTCH, FPORTEN) VALUES (12, '广州', 'GUANGZHOU');

COMMIT WORK;
