SET NAMES NONE;
SET SQL DIALECT 3;

CREATE DATABASE 'LOCALHOST:C:\TEMP\FBBUG2\BUG2.FDB' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 1024;

/* Table A */

CREATE TABLE A (
    ID  INTEGER NOT NULL,
    NZ   DOUBLE PRECISION,
    PZ   DOUBLE PRECISION,
    NZI  DOUBLE PRECISION,
    PZI  DOUBLE PRECISION
);

ALTER TABLE A ADD CONSTRAINT A_PK PRIMARY KEY (ID);

CREATE INDEX A_NZI ON A (NZI);

CREATE INDEX A_PZI ON A (PZI);

INSERT INTO A (ID, NZ, PZ, NZI, PZI) VALUES (1, -0E0, 0E0, -0E0, 0E0);


/* Table B */

CREATE TABLE B (
    F1  DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX B_F1_U ON B (F1);
