SET SQL DIALECT 3;

SET NAMES ISO8859_1;

SET CLIENTLIB 'fbclient.dll';

CREATE DATABASE 'C:\temp\BUG.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET ISO8859_1 COLLATION ISO8859_1;

/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/

CREATE TABLE ASSOCIATE_TABLE (
    ID  INTEGER NOT NULL
);

CREATE TABLE MAIN_TABLE (
    ID  INTEGER GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE RELATION_TABLE (
    ID_MAIN_TABLE        INTEGER NOT NULL,
    ID_ASSOCIATE_TABLE  INTEGER NOT NULL
);

/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE ASSOCIATE_TABLE ADD CONSTRAINT PK_ASSOCIATE_TABLE PRIMARY KEY (ID);
ALTER TABLE MAIN_TABLE ADD CONSTRAINT PK_MAIN_TABLE PRIMARY KEY (ID);
ALTER TABLE RELATION_TABLE ADD CONSTRAINT PK_RELATION_TABLE PRIMARY KEY (ID_MAIN_TABLE, ID_ASSOCIATE_TABLE);

/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE RELATION_TABLE ADD CONSTRAINT FK_RELATION_TABLE_1 FOREIGN KEY (ID_MAIN_TABLE) REFERENCES MAIN_TABLE (ID) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RELATION_TABLE ADD CONSTRAINT FK_RELATION_TABLE_2 FOREIGN KEY (ID_ASSOCIATE_TABLE) REFERENCES ASSOCIATE_TABLE (ID) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT WORK;

INSERT INTO ASSOCIATE_TABLE (ID) VALUES (1);
INSERT INTO ASSOCIATE_TABLE (ID) VALUES (2);
INSERT INTO ASSOCIATE_TABLE (ID) VALUES (3);
INSERT INTO ASSOCIATE_TABLE (ID) VALUES (4);
INSERT INTO ASSOCIATE_TABLE (ID) VALUES (5);
INSERT INTO ASSOCIATE_TABLE (ID) VALUES (6);

COMMIT WORK;
