SET NAMES ISO8859_1;
        
SET SQL DIALECT 3;

UPDATE OR INSERT INTO MAIN_TABLE(ID) VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM MAIN_TABLE));
ALTER TABLE MAIN_TABLE ALTER ID RESTART WITH 1;
UPDATE OR INSERT INTO RELATION_TABLE(ID_MAIN_TABLE, ID_ASSOCIATE_TABLE) VALUES (1, 1);

UPDATE OR INSERT INTO MAIN_TABLE(ID) VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM MAIN_TABLE));
ALTER TABLE MAIN_TABLE ALTER ID RESTART WITH 2;
UPDATE OR INSERT INTO RELATION_TABLE(ID_MAIN_TABLE, ID_ASSOCIATE_TABLE) VALUES (2, 2);

COMMIT WORK;

UPDATE OR INSERT INTO MAIN_TABLE(ID) VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM MAIN_TABLE));
ALTER TABLE MAIN_TABLE ALTER ID RESTART WITH 3;
UPDATE OR INSERT INTO RELATION_TABLE(ID_MAIN_TABLE, ID_ASSOCIATE_TABLE) VALUES (3, 3);

UPDATE OR INSERT INTO MAIN_TABLE(ID) VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM MAIN_TABLE));
ALTER TABLE MAIN_TABLE ALTER ID RESTART WITH 4;
UPDATE OR INSERT INTO RELATION_TABLE(ID_MAIN_TABLE, ID_ASSOCIATE_TABLE) VALUES (4, 4);

COMMIT WORK;

UPDATE OR INSERT INTO MAIN_TABLE(ID) VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM MAIN_TABLE));
ALTER TABLE MAIN_TABLE ALTER ID RESTART WITH 5;
UPDATE OR INSERT INTO RELATION_TABLE(ID_MAIN_TABLE, ID_ASSOCIATE_TABLE) VALUES (5, 5);

COMMIT WORK;

UPDATE OR INSERT INTO MAIN_TABLE(ID) VALUES ((SELECT COALESCE(MAX(ID), 0) + 1 FROM MAIN_TABLE));
ALTER TABLE MAIN_TABLE ALTER ID RESTART WITH 6;
UPDATE OR INSERT INTO RELATION_TABLE(ID_MAIN_TABLE, ID_ASSOCIATE_TABLE) VALUES (6, 6);

COMMIT WORK;

DELETE FROM MAIN_TABLE;
