
SET SQL DIALECT 3;

SET NAMES WIN1251;

CONNECT '127.0.0.1:PMRMK' USER 'SYSDBA' PASSWORD 'masterkey';


CREATE DOMAIN D_BARCODE AS
VARCHAR(13);

CREATE DOMAIN D_BOOLEAN AS
SMALLINT;

CREATE DOMAIN D_CODE AS
VARCHAR(7);

CREATE DOMAIN D_DATETIME AS
TIMESTAMP;

CREATE DOMAIN D_IDENTITY AS
BIGINT;

CREATE DOMAIN D_IDPOS AS
BIGINT;

CREATE DOMAIN D_ID_NPRICE AS
BIGINT;

CREATE DOMAIN D_INT AS
INTEGER;

CREATE DOMAIN D_KP_10 AS
VARCHAR(10);

CREATE DOMAIN D_MONEY AS
NUMERIC(18,2);

CREATE DOMAIN D_NAME_80 AS
VARCHAR(80);

CREATE DOMAIN D_NAME_COUNT AS
VARCHAR(20);

CREATE DOMAIN D_NAME_COU_S AS
VARCHAR(5);

CREATE DOMAIN D_NAME_PRO_20 AS
VARCHAR(20);

CREATE DOMAIN D_NONUNIQUE AS
VARCHAR(1);

CREATE DOMAIN D_OTDEL AS
VARCHAR(2);

CREATE DOMAIN D_PRIM_50 AS
VARCHAR(50);

CREATE DOMAIN D_PRIZNAK AS
VARCHAR(1);

CREATE DOMAIN D_SERIY_15 AS
VARCHAR(15);

CREATE TABLE CONFIG (
    ID                D_IDENTITY NOT NULL,
    MASTER            VARCHAR(15) NOT NULL COLLATE PXW_CYRL,
    SELF              VARCHAR(15) NOT NULL COLLATE PXW_CYRL,
    ID_NPRICE         BIGINT DEFAULT 0 NOT NULL,
    EXCHANGE          VARCHAR(127) DEFAULT 'C:\EXCHANGE\' NOT NULL,
    TEMP              VARCHAR(127) DEFAULT 'C:\ACCEPTANCE\TEMP\' NOT NULL,
    DISCOUNT_DATE     D_DATETIME DEFAULT '30-DEC-1899' NOT NULL,
    PRICE_DATE        D_DATETIME DEFAULT '30-DEC-1899' NOT NULL,
    PINPAD            D_BOOLEAN DEFAULT 0 NOT NULL,
    REPLENISHMENT     D_BOOLEAN DEFAULT 0 NOT NULL,
    FILEVERSION       VARCHAR(15) DEFAULT '0.0.0.0' NOT NULL,
    FRPRINTSRV        VARCHAR(15) DEFAULT '0.0.0.0' NOT NULL,
    CARDS_DATE        D_DATETIME DEFAULT '30-DEC-1899' NOT NULL,
    FONT_INCREASE     INTEGER DEFAULT 0 NOT NULL,
    CASHREG_RESPONSE  VARCHAR(127) DEFAULT 'X:\' NOT NULL
);

ALTER TABLE CONFIG ADD CONSTRAINT PK_CONFIG PRIMARY KEY (ID);

INSERT INTO CONFIG (ID, MASTER, SELF, ID_NPRICE, EXCHANGE, TEMP, DISCOUNT_DATE, PRICE_DATE, PINPAD, REPLENISHMENT, FILEVERSION, FRPRINTSRV, CARDS_DATE, FONT_INCREASE, CASHREG_RESPONSE)
VALUES (0, '127.0.0.1', '127.0.0.1', 101, 'C:\EXCHANGE\', 'C:\ACCEPTANCE\TEMP\', '2012-12-13 16:03:28', '2012-04-04 23:30:51', 1, 0, '1.7.1.2', '1.7.0.7', '1899-12-30 00:00:00', 0, 'X:\');


SET TERM ^ ;

CREATE OR ALTER PROCEDURE SPDUMPCONFIG
AS
DECLARE VARIABLE MASTER VARCHAR(15);
DECLARE VARIABLE SELF VARCHAR(15);
BEGIN
  SELECT MASTER, SELF FROM CONFIG INTO :MASTER, :SELF;

  EXECUTE STATEMENT '
EXECUTE BLOCK
AS
DECLARE VARIABLE MASTER         VARCHAR(15);
DECLARE VARIABLE SELF           VARCHAR(15);
DECLARE VARIABLE ID_NPRICE      BIGINT;
DECLARE VARIABLE EXCHANGE       VARCHAR(127);
DECLARE VARIABLE TEMP           VARCHAR(127);
DECLARE VARIABLE DISCOUNT_DATE  D_DATETIME;
DECLARE VARIABLE PRICE_DATE     D_DATETIME;
DECLARE VARIABLE PINPAD         D_BOOLEAN;
DECLARE VARIABLE REPLENISHMENT  D_BOOLEAN;
DECLARE VARIABLE FILEVERSION    VARCHAR(15);
DECLARE VARIABLE FRPRINTSRV     VARCHAR(15);
DECLARE VARIABLE CARDS_DATE     D_DATETIME;
DECLARE VARIABLE KKM_NUMBER     VARCHAR(10);
DECLARE VARIABLE FONT_INCREASE  INTEGER;
BEGIN
  FOR
    EXECUTE STATEMENT ''
    SELECT MASTER,SELF,ID_NPRICE,EXCHANGE,TEMP,DISCOUNT_DATE,PRICE_DATE,PINPAD,REPLENISHMENT,FILEVERSION,FRPRINTSRV,CARDS_DATE,KKM_NUMBER,0 FONT_INCREASE
    FROM CONFIG ''
  ON EXTERNAL DATA SOURCE '''|| :SELF || '''||''/3050:PMRMK''
  WITH COMMON TRANSACTION
  AS USER ''SYSDBA'' PASSWORD ''masterkey''
  INTO :MASTER,:SELF,:ID_NPRICE,:EXCHANGE,:TEMP,:DISCOUNT_DATE,:PRICE_DATE,:PINPAD,:REPLENISHMENT,:FILEVERSION,:FRPRINTSRV,:CARDS_DATE,:KKM_NUMBER,:FONT_INCREASE
  DO
  BEGIN
    UPDATE OR INSERT INTO CONFIG(MASTER,SELF,ID_NPRICE,EXCHANGE,TEMP,DISCOUNT_DATE,PRICE_DATE,PINPAD,REPLENISHMENT,FILEVERSION,FRPRINTSRV,CARDS_DATE,KKM_NUMBER,FONT_INCREASE)
    VALUES(:MASTER,:SELF,:ID_NPRICE,:EXCHANGE,:TEMP,:DISCOUNT_DATE,:PRICE_DATE,:PINPAD,:REPLENISHMENT,:FILEVERSION,:FRPRINTSRV,:CARDS_DATE,:KKM_NUMBER,:FONT_INCREASE)
    MATCHING(SELF);
    SUSPEND;
  END
END '
  ON EXTERNAL DATA SOURCE :MASTER||'/3050:ACCEPTANCE'
  WITH COMMON TRANSACTION
  AS USER 'SYSDBA' PASSWORD 'masterkey';

  WHEN ANY DO EXIT;
END^



SET TERM ; ^
