/******************************************************************************/
/***          Generated by IBExpert 2011.09.02 05.06.2013 11:59:46          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;

CONNECT '127.0.0.1:ACCEPTANCE' USER 'SYSDBA' PASSWORD 'masterkey';



/******************************************************************************/
/***                                Domains                                 ***/
/******************************************************************************/

CREATE DOMAIN D_IDENTITY AS
BIGINT
NOT NULL;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CONFIG (
    ID             D_IDENTITY NOT NULL,
    MASTER         VARCHAR(15) NOT NULL,
    SELF           VARCHAR(15) NOT NULL,
    ID_NPRICE      BIGINT DEFAULT 0 NOT NULL,
    EXCHANGE       VARCHAR(127) DEFAULT 'C:\EXCHANGE\' NOT NULL,
    TEMP           VARCHAR(127) DEFAULT 'C:\ACCEPTANCE\TEMP\' NOT NULL,
    DISCOUNT_DATE  D_DATETIME DEFAULT '30-DEC-1899' NOT NULL,
    PRICE_DATE     D_DATETIME DEFAULT '30-DEC-1899' NOT NULL,
    PINPAD         D_BOOLEAN DEFAULT 0 NOT NULL,
    REPLENISHMENT  D_BOOLEAN DEFAULT 0 NOT NULL,
    FILEVERSION    VARCHAR(15) DEFAULT '0.0.0.0' NOT NULL,
    FRPRINTSRV     VARCHAR(15) DEFAULT '0.0.0.0' NOT NULL,
    CARDS_DATE     D_DATETIME DEFAULT '30-DEC-1899' NOT NULL,
    KKM_NUMBER     VARCHAR(10) DEFAULT ' ' NOT NULL,
    FONT_INCREASE  INTEGER DEFAULT 0 NOT NULL
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CONFIG ADD CONSTRAINT PK_CONFIG PRIMARY KEY (ID);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE UNIQUE INDEX CONFIG_IDX ON CONFIG (SELF);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CONFIG_BI */
CREATE OR ALTER TRIGGER CONFIG_BI FOR CONFIG
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(G_CONFIG_ID,1);
END
^


SET TERM ; ^

