/******************************************************************************/
/****        Generated by IBExpert 2012.11.26.1 05.12.2012 13:32:46        ****/
/******************************************************************************/

/******************************************************************************/
/****     Following SET SQL DIALECT is just for the Database Comparer      ****/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN "DOMSYS_DBBEZ" AS
VARCHAR(32) CHARACTER SET UTF8;

CREATE DOMAIN "DOMSYS_DBPERM" AS
CHAR(1) CHARACTER SET UTF8
CHECK (VALUE IN ('S','I','U','D','E','R','M'));

CREATE DOMAIN "DOMSYS_DBSTATUS" AS
VARCHAR(12) CHARACTER SET UTF8
NOT NULL;

CREATE DOMAIN "DOM_ABC" AS
CHAR(1) CHARACTER SET UTF8
DEFAULT 'B'
CHECK (VALUE IN ('A','B','C'));

CREATE DOMAIN "DOM_BETRAG" AS
DECIMAL(15,2);

CREATE DOMAIN "DOM_BEZEICHNUNG" AS
VARCHAR(80) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_BEZKURZ" AS
VARCHAR(35) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_BEZLAENGER" AS
VARCHAR(500) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_BEZLANG" AS
VARCHAR(320) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_BOOLEAN_F" AS
SMALLINT
DEFAULT 0;

CREATE DOMAIN "DOM_BOOLEAN_T" AS
SMALLINT
DEFAULT 1;

CREATE DOMAIN "DOM_CHANGEDAT" AS
TIMESTAMP
DEFAULT current_timestamp;

CREATE DOMAIN "DOM_CHANGEDBY" AS
VARCHAR(18) CHARACTER SET UTF8
DEFAULT USER;

CREATE DOMAIN "DOM_CHANGEDROLE" AS
VARCHAR(18) CHARACTER SET UTF8
DEFAULT current_role;

CREATE DOMAIN "DOM_CNFDATUM" AS
DATE;

CREATE DOMAIN "DOM_CNFSTRING" AS
VARCHAR(8100) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_CNFZAHL" AS
BIGINT;

CREATE DOMAIN "DOM_DATUM" AS
DATE;

CREATE DOMAIN "DOM_GESCHLECHT" AS
SMALLINT
DEFAULT 0
NOT NULL
CHECK ((VALUE BETWEEN 0 AND 4));

CREATE DOMAIN "DOM_HILFETEXT" AS
VARCHAR(8100) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_ICON" AS
BLOB SUB_TYPE 0 SEGMENT SIZE 80;

CREATE DOMAIN "DOM_KEY" AS
BIGINT
DEFAULT 0;

CREATE DOMAIN "DOM_KUERZEL" AS
VARCHAR(10) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_Memo" AS
VARCHAR(4000) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_OBJREF" AS
CHAR(3) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_ORGNUMMER" AS
VARCHAR(10) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_ORT" AS
VARCHAR(50) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_PLZ" AS
VARCHAR(10) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_PRCAKT" AS
SMALLINT;

CREATE DOMAIN "DOM_PRCMSG" AS
VARCHAR(8100) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_PRCSTATUS" AS
SMALLINT
DEFAULT 0
NOT NULL;

CREATE DOMAIN "DOM_VERSION" AS
BIGINT
DEFAULT 1;

CREATE DOMAIN "DOM_WVTEST" AS
VARCHAR(8100) CHARACTER SET UTF8;

CREATE DOMAIN "DOM_ZAHL" AS
SMALLINT;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE SEQUENCE "GEN_CNFSYS_ID";
CREATE SEQUENCE "GEN_CNFUSR_ID";
CREATE SEQUENCE "GEN_DBUSER_ID";


/******************************************************************************/
/****                              Exceptions                              ****/
/******************************************************************************/

CREATE EXCEPTION "CANTDELETE0" 'Kann Datensatz mit SchlÃƒÂ¼ssel (Id) 0 nicht lÃƒÂ¶schen';

CREATE EXCEPTION "INTERNALERROR" 'Interner Fehler';

CREATE EXCEPTION "NOTALLOWED" 'Berechtigung fehlt';

CREATE EXCEPTION "PARAMINVALID" 'Eingabeparameter ungÃƒÂ¼ltig';



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE "CNFSYS" (
    "Id"                       "DOM_KEY" NOT NULL,
    "Schluessel"               "DOM_BEZEICHNUNG",
    "WertStr"                  "DOM_CNFSTRING",
    "WertDat"                  "DOM_CNFDATUM",
    "WertInt"                  "DOM_CNFZAHL",
    "IstAktiv"                 "DOM_BOOLEAN_F" NOT NULL,
    "AutoAngelegtVon"          "DOM_CHANGEDBY",
    "AutoAngelegtRole"         "DOM_CHANGEDROLE",
    "AutoAngelegtAm"           "DOM_CHANGEDAT",
    "AutoLetzteAenderungVon"   "DOM_CHANGEDBY",
    "AutoLetzteAenderungRole"  "DOM_CHANGEDROLE",
    "AutoLetzteAenderungAm"    "DOM_CHANGEDAT"
);


CREATE TABLE "CNFUSR" (
    "Id"                       "DOM_KEY" NOT NULL,
    "RefUser"                  "DOM_KEY",
    "Schluessel"               "DOM_BEZEICHNUNG",
    "WertStr"                  "DOM_CNFSTRING",
    "WertDat"                  "DOM_CNFDATUM",
    "WertInt"                  "DOM_CNFZAHL",
    "IstAktiv"                 "DOM_BOOLEAN_F" NOT NULL,
    "AutoAngelegtVon"          "DOM_CHANGEDBY",
    "AutoAngelegtRole"         "DOM_CHANGEDROLE",
    "AutoAngelegtAm"           "DOM_CHANGEDAT",
    "AutoLetzteAenderungVon"   "DOM_CHANGEDBY",
    "AutoLetzteAenderungRole"  "DOM_CHANGEDROLE",
    "AutoLetzteAenderungAm"    "DOM_CHANGEDAT"
);


CREATE TABLE "DBUSER" (
    "Id"                       "DOM_KEY" NOT NULL,
    "UserName"                 "DOM_BEZEICHNUNG",
    "Vorname"                  "DOM_BEZEICHNUNG",
    "Nachname"                 "DOM_BEZEICHNUNG",
    "ErstesLogin"              "DOM_CHANGEDAT",
    "LetztesLogin"             "DOM_CHANGEDAT",
    "LetztesLogout"            "DOM_CHANGEDAT",
    "IstGesperrt"              "DOM_BOOLEAN_F" NOT NULL,
    "AutoAngelegtVon"          "DOM_CHANGEDBY",
    "AutoAngelegtRole"         "DOM_CHANGEDROLE",
    "AutoAngelegtAm"           "DOM_CHANGEDAT",
    "AutoLetzteAenderungVon"   "DOM_CHANGEDBY",
    "AutoLetzteAenderungRole"  "DOM_CHANGEDROLE",
    "AutoLetzteAenderungAm"    "DOM_CHANGEDAT"
);




/******************************************************************************/
/****                          Unique Constraints                          ****/
/******************************************************************************/

ALTER TABLE "CNFSYS" ADD CONSTRAINT "UNQ_CNFSYS" UNIQUE ("Schluessel");
ALTER TABLE "CNFUSR" ADD CONSTRAINT "UNQ_CNFUSR" UNIQUE ("RefUser", "Schluessel");


/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE "CNFSYS" ADD CONSTRAINT "PK_CNFSYS" PRIMARY KEY ("Id");
ALTER TABLE "CNFUSR" ADD CONSTRAINT "PK_CNFUSR" PRIMARY KEY ("Id");
ALTER TABLE "DBUSER" ADD CONSTRAINT "PK_DBUSER" PRIMARY KEY ("Id");


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE "CNFUSR" ADD CONSTRAINT "FK_CNFUSR_RefUser" FOREIGN KEY ("RefUser") REFERENCES "DBUSER" ("Id") ON DELETE CASCADE ON UPDATE CASCADE;


/******************************************************************************/
/****                               Indices                                ****/
/******************************************************************************/

CREATE UNIQUE INDEX "IDX_DBUSER_UN" ON "DBUSER" ("UserName");


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: "CNFUSR_BIU0" */
CREATE OR ALTER TRIGGER "CNFUSR_BIU0" FOR "CNFUSR"
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
as
begin
  if ((new."Id" is null) or (new."Id"  <= 0)) then
    new."Id" = gen_id(GEN_CNFUSR_ID,1);


  if ((current_user <> 'SYSDBA') and
      (current_role <> 'DBA')) then begin
    if (inserting) then begin
      new."AutoAngelegtAm" = current_timestamp;
      new."AutoAngelegtVon" = current_user;
      new."AutoAngelegtRole" = current_role;
    end
    else begin
      new."AutoAngelegtAm" = old."AutoAngelegtAm";
      new."AutoAngelegtVon" = old."AutoAngelegtVon";
      new."AutoAngelegtRole" = old."AutoAngelegtRole";
    end
    new."AutoLetzteAenderungAm" = current_timestamp;
    new."AutoLetzteAenderungVon" = current_user;
    new."AutoLetzteAenderungRole" = current_role;
  end
end;


/* Trigger: "DBUSER_BD0" */
CREATE OR ALTER TRIGGER "DBUSER_BD0" FOR "DBUSER"
ACTIVE BEFORE DELETE POSITION 0
as
begin
  if (old."Id" = 0) then
    exception CANTDELETE0;
end;


/* Trigger: "DBUSER_BIU0" */
CREATE OR ALTER TRIGGER "DBUSER_BIU0" FOR "DBUSER"
ACTIVE BEFORE INSERT OR UPDATE POSITION 0
as
begin
  if ((new."Id" is null) or (new."Id"  <= -10)) then  -- Achtung, geandertes Verhalten; Neue Id nur f�r Id < -10
    new."Id" = gen_id(GEN_DBUSER_ID,1);

  if ((current_user <> 'SYSDBA') and
      (current_role <> 'DBA')) then begin
    if (inserting) then begin
      new."AutoAngelegtAm" = current_timestamp;
      new."AutoAngelegtVon" = current_user;
      new."AutoAngelegtRole" = current_role;
    end
    else begin
      new."AutoAngelegtAm" = old."AutoAngelegtAm";
      new."AutoAngelegtVon" = old."AutoAngelegtVon";
      new."AutoAngelegtRole" = old."AutoAngelegtRole";
    end
    new."AutoLetzteAenderungAm" = current_timestamp;
    new."AutoLetzteAenderungVon" = current_user;
    new."AutoLetzteAenderungRole" = current_role;
  end
end;




/******************************************************************************/
/****                                Roles                                 ****/
/******************************************************************************/

CREATE ROLE "GURU";
CREATE ROLE "LESEN";


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON "CNFSYS" TO "FAUMETA" WITH GRANT OPTION;
GRANT ALL ON "CNFUSR" TO "FAUMETA" WITH GRANT OPTION;
GRANT ALL ON "DBUSER" TO "FAUMETA" WITH GRANT OPTION;
GRANT "LESEN" TO "LO35ZAVY";
GRANT "LESEN" TO "UNRZ62";
GRANT ALL ON "CNFSYS" TO "ZUVF1DB" WITH GRANT OPTION;
GRANT ALL ON "CNFUSR" TO "ZUVF1DB" WITH GRANT OPTION;
GRANT ALL ON "DBUSER" TO "ZUVF1DB" WITH GRANT OPTION;
GRANT "GURU" TO "ZUVF1DB";
GRANT "LESEN" TO "ZUVF1DB";

/* Privileges of triggers */
GRANT UPDATE, REFERENCES ON "DBUSER" TO TRIGGER "DBUSER_BIU0";