SET NAMES NONE;
SET SQL DIALECT 3;

CREATE DATABASE '...testidx.fdb' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 1024;

CREATE TABLE T1 (
    F1  INTEGER NOT NULL,
    F2  INTEGER NOT NULL,
    F3  INTEGER NOT NULL,
    F4  INTEGER NOT NULL,
    F5  INTEGER NOT NULL,
    F6  INTEGER NOT NULL,
    F7  INTEGER NOT NULL,
    F8  INTEGER NOT NULL,
    F9  INTEGER NOT NULL,
    D1  DATE NOT NULL,
    D2  DATE NOT NULL,
    D3  DATE NOT NULL,
    D4  DATE NOT NULL,
    D5  DATE NOT NULL,
    D6  DATE NOT NULL,
    D7  DATE NOT NULL,
    D8  DATE NOT NULL,
    D9  DATE NOT NULL,
    C1  VARCHAR(64) NOT NULL,
    C2  VARCHAR(64) NOT NULL,
    C3  VARCHAR(64) NOT NULL,
    C4  VARCHAR(64) NOT NULL,
    C5  VARCHAR(64) NOT NULL,
    C6  VARCHAR(64) NOT NULL,
    C7  VARCHAR(64) NOT NULL,
    C8  VARCHAR(64) NOT NULL,
    C9  VARCHAR(64) NOT NULL
);


ALTER TABLE T1 ADD CONSTRAINT PK_T1 PRIMARY KEY (F1);
CREATE INDEX T1_IDX_F2 ON T1 (F2);

SET TERM ^ ;

CREATE PROCEDURE T1_FILL (CNT INTEGER)
AS
DECLARE VARIABLE D DATE;
DECLARE VARIABLE C VARCHAR(64);
BEGIN
  WHILE (CNT > 0)
  DO BEGIN
    D = CURRENT_DATE;
    C = CAST(D AS VARCHAR(64));

    INSERT INTO T1 (
      F1, F2, F3, F4, F5, F6, F7, F8, F9,
      D1, D2, D3, D4, D5, D6, D7, D8, D9,
      C1, C2, C3, C4, C5, C6, C7, C8, C9
    ) VALUES (
      :CNT, 2001, :CNT, :CNT, :CNT, :CNT, :CNT, :CNT, :CNT,
      :D, :D, :D, :D, :D, :D, :D, :D, :D,
      :C, :C, :C, :C, :C, :C, :C, :C, :C
    );

    CNT = CNT - 1;
  END
END
^


SET TERM ; ^

EXIT;
