/******************************************************************************/
/****         Generated by IBExpert 2011.09.05 06/09/2017 16:17:35         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE 'C:\base\TESTFB3.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_TEST_ID;
SET GENERATOR GEN_TEST_ID TO 3;



SET TERM ^ ; 



/******************************************************************************/
/****                          Stored Procedures                           ****/
/******************************************************************************/

CREATE OR ALTER PROCEDURE COPY_RECORD (
    OLDID INTEGER)
RETURNS (
    NEWID INTEGER)
AS
BEGIN
  SUSPEND;
END^





CREATE OR ALTER PROCEDURE RUN_TEST
RETURNS (
    ID INTEGER,
    F1 VARCHAR(100))
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TEST (
    ID  INTEGER NOT NULL,
    F1  VARCHAR(100)
);

INSERT INTO TEST (ID, F1) VALUES (1, 'TEST');
INSERT INTO TEST (ID, F1) VALUES (2, 'TEST (COPY)');
INSERT INTO TEST (ID, F1) VALUES (3, 'TEST (COPY)');

COMMIT WORK;



/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE TEST ADD CONSTRAINT PK_TEST PRIMARY KEY (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TEST_BI */
CREATE OR ALTER TRIGGER TEST_BI FOR TEST
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TEST_ID,1);
END
^

SET TERM ; ^



/******************************************************************************/
/****                          Stored Procedures                           ****/
/******************************************************************************/


SET TERM ^ ;

CREATE OR ALTER PROCEDURE COPY_RECORD (
    OLDID INTEGER)
RETURNS (
    NEWID INTEGER)
AS
BEGIN
  INSERT INTO TEST (ID, F1)
  SELECT NULL, F1 || ' (COPY)'
  FROM TEST
  WHERE ID = :OLDID
  RETURNING ID
  INTO NEWID;
  SUSPEND;
END^


CREATE OR ALTER PROCEDURE RUN_TEST
RETURNS (
    ID INTEGER,
    F1 VARCHAR(100))
AS
begin
  SELECT ID, F1 FROM COPY_RECORD(1) T1
  INNER JOIN TEST ON (ID = T1.NEWID)
  INTO ID, F1;
  suspend;
end^



SET TERM ; ^
