#!/bin/sh
#

# This file belongs in /etc/init.d where it will be run
# on system startup and shutdown to start the background
# Firebird/interbase database server daemon 

mode=$1

PATH=$PATH:/usr/local/firebird/bin
export PATH
LD_LIBRARY_PATH=/usr/local/firebird/lib:/usr/local/firebird/intl
export LD_LIBRARY_PATH
INTERBASE=/usr/local/firebird
export INTERBASE

FIREBIRD=/usr/local/firebird

export FIREBIRD

usage_error() {
      echo "  $0 start             (start Firebird SS server process)"
      echo "  $0 stop              (stop Firebird SS server process)"
      echo " "
}

if [ ! -d /usr/local/firebird ]
then
	echo "Firebird SS directory /usr/local/firebird does not exist!"
	exit 1
fi

case "$mode" in

'start')
	echo "trying to start Firebird SS Server.."
	${FIREBIRD}/bin/fbmgr.bin -start -forever
	;;

'stop') 	
	echo "trying to stop Firebird SS Server.."
	pkill fbserver
	sleep 1

	;;

*)
	usage_error
	exit 1
	;;
esac

exit 0
