SET NAMES WIN1251;

CREATE DATABASE 'TERRA:test2.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1251;


CREATE TABLE TEST_TABLE (
    FIELD_01  INTEGER NOT NULL,
    FIELD_02  VARCHAR(10) NOT NULL
);

INSERT INTO TEST_TABLE (FIELD_01, FIELD_02) VALUES (1, 'Data 1');
INSERT INTO TEST_TABLE (FIELD_01, FIELD_02) VALUES (2, 'Data 2');

COMMIT WORK;

ALTER TABLE TEST_TABLE
   ADD FIELD_03 VARCHAR(10) NOT NULL;

