
CREATE DATABASE 'C:\test.fdb' USER 'SYSDBA' PASSWORD 'masterkey';

DROP PROCEDURE good;
DROP PROCEDURE bad;

RECREATE TABLE t (
  id INTEGER NOT NULL PRIMARY KEY,
  s VARCHAR(50)
);
CREATE INDEX idx ON t(s);

INSERT INTO t VALUES (1, '');
INSERT INTO t VALUES (2, 'X');

SET TERM ;; ;

CREATE OR ALTER PROCEDURE good RETURNS (id INTEGER) AS
BEGIN
  FOR SELECT id FROM t WHERE s STARTING WITH '' INTO :id DO SUSPEND;
END;;

CREATE OR ALTER PROCEDURE bad RETURNS (id INTEGER) AS
  DECLARE v VARCHAR(50) = '';
BEGIN
  FOR SELECT id FROM t WHERE s STARTING WITH :v INTO :id DO SUSPEND;
END;;
