CREATE TABLE BLOB_TABLE (
    ID           INTEGER NOT NULL,
    TEXT_VALUE   VARCHAR(50),
    BLOB_VALUE   BLOB SUB_TYPE 1 SEGMENT SIZE 80
);
COMMIT;

CREATE VIEW BLOB_VIEW(
    ID,
    TEXT_VALUE,
    BLOB_VALUE)
AS
SELECT ID, TEXT_VALUE, BLOB_VALUE,BLOB_BINARY FROM BLOB_TABLE;
COMMIT;

ALTER TABLE BLOB_TABLE ADD CONSTRAINT PK_BLOB_TABLE PRIMARY KEY (ID);
COMMIT;

SET TERM ^ ;

CREATE OR ALTER TRIGGER BIUD_BLOB_VIEW FOR BLOB_VIEW
ACTIVE BEFORE INSERT OR UPDATE OR DELETE POSITION 0
AS
BEGIN
  if (INSERTING) then
  begin
    INSERT INTO BLOB_TABLE(
      ID,
      TEXT_VALUE,
      BLOB_VALUE)
    values (
      new.ID,
      new.TEXT_VALUE,
      new.BLOB_VALUE);
  end

  if (UPDATING) then
  begin
    UPDATE BLOB_TABLE SET
      TEXT_VALUE = new.TEXT_VALUE,
      BLOB_VALUE = new.BLOB_VALUE
    WHERE
      ID = old.ID;
  end

  if (DELETING) then
    delete from BLOB_TABLE
    WHERE
      ID = old.ID;
END^

COMMIT^

SET TERM ; ^

GRANT ALL ON BLOB_VIEW TO PUBLIC;
GRANT ALL ON BLOB_TABLE TO TRIGGER BIUD_BLOB_VIEW;
COMMIT;

INSERT INTO BLOB_TABLE (ID, TEXT_VALUE, BLOB_VALUE) VALUES (1, 'test data', x'414243')
COMMIT;
