/*******************************************************************************
The next statement causes the following error: 

Access violation at address 10030E2B in module 'fbclient.dll'. Read of address 00000008
*******************************************************************************/
commit;

These are the lines in my script before the commit:
alter table t_ergebnisdaten add f_haftungsklasse INTEGER DEFAULT 0;
alter table t_ergebnisdaten add f_kommentar varchar(1000);
alter table t_ergebnisdaten add F_FH VARCHAR(50);
alter table t_ergebnisdaten add F_FH_VON DOUBLE PRECISION DEFAULT -1;
alter table t_ergebnisdaten add F_FH_BIS DOUBLE PRECISION DEFAULT -1;
alter table t_ergebnisdaten add F_FH_EINHEIT VARCHAR(15);
alter table t_ergebnisdaten add F_SCHICHTDICKE VARCHAR(50);
alter table t_ergebnisdaten add F_SCHICHTDICKE_VON DOUBLE PRECISION DEFAULT -1;
alter table t_ergebnisdaten add F_SCHICHTDICKE_BIS DOUBLE PRECISION DEFAULT -1;
alter table t_ergebnisdaten add F_SCHICHTDICKE_EINHEIT VARCHAR(15);

update t_ergebnisdaten set f_haftungsklasse=0,F_FH_VON =-1,F_FH_BIS=-1, F_SCHICHTDICKE_VON=-1, F_SCHICHTDICKE_BIS=-1;
update t_ergebnisdaten t1 set f_kommentar = (select f_kommentar from t_pruefergebnis_apos t2 where t1.id_ergebnisdaten = t2.f_id_ergebnisdaten) where id_ergebnisdaten in (select f_id_ergebnisdaten from t_pruefergebnis_apos where f_kommentar is not null and f_kommentar != '');
update t_ergebnisdaten t1 set f_kommentar = (select f_kommentar from t_pruefergebnis_wbhcharge t2 where t1.id_ergebnisdaten = t2.f_id_ergebnisdaten) where id_ergebnisdaten in (select f_id_ergebnisdaten from t_pruefergebnis_wbhcharge where f_kommentar is not null and f_kommentar != '');
commit;

DDL:
/******************************************************************************/
/***               Generated by IBExpert 04.07.2006 09:23:51                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE T_ERGEBNISDATEN (
    ID_ERGEBNISDATEN              INTEGER NOT NULL,
    F_KH                          VARCHAR(50),
    F_KH_VON                      DOUBLE PRECISION DEFAULT -1,
    F_KH_BIS                      DOUBLE PRECISION DEFAULT -1,
    F_KH_EINHEIT                  VARCHAR(15),
    F_NITRIERHAERTETIEFE          VARCHAR(50),
    F_NITRIERHAERTETIEFE_VON      DOUBLE PRECISION DEFAULT -1,
    F_NITRIERHAERTETIEFE_BIS      DOUBLE PRECISION DEFAULT -1,
    F_NITRIERHAERTETIEFE_EINHEIT  VARCHAR(15),
    F_EINHAERTETIEFE              VARCHAR(50),
    F_EINHAERTETIEFE_VON          DOUBLE PRECISION DEFAULT -1,
    F_EINHAERTETIEFE_BIS          DOUBLE PRECISION DEFAULT -1,
    F_EINHAERTETIEFE_EINHEIT      VARCHAR(15),
    F_EINSATZHAERTETIEFE          VARCHAR(50),
    F_EINSATZHAERTETIEFE_VON      DOUBLE PRECISION DEFAULT -1,
    F_EINSATZHAERTETIEFE_BIS      DOUBLE PRECISION DEFAULT -1,
    F_EINSATZHAERTETIEFE_EINHEIT  VARCHAR(15),
    F_DSD                         VARCHAR(50),
    F_DSD_BIS                     DOUBLE PRECISION DEFAULT -1,
    F_DSD_VON                     DOUBLE PRECISION DEFAULT -1,
    F_DSD_EINHEIT                 VARCHAR(15),
    F_OSD                         VARCHAR(50),
    F_OSD_BIS                     DOUBLE PRECISION DEFAULT -1,
    F_OSD_VON                     DOUBLE PRECISION DEFAULT -1,
    F_OSD_EINHEIT                 VARCHAR(15),
    F_VSD                         VARCHAR(50),
    F_VSD_BIS                     DOUBLE PRECISION DEFAULT -1,
    F_VSD_VON                     DOUBLE PRECISION DEFAULT -1,
    F_VSD_EINHEIT                 VARCHAR(15),
    F_RH                          VARCHAR(50),
    F_RH_VON                      DOUBLE PRECISION DEFAULT -1,
    F_RH_BIS                      DOUBLE PRECISION DEFAULT -1,
    F_RH_EINHEIT                  VARCHAR(15),
    F_GH                          VARCHAR(50),
    F_GH_VON                      DOUBLE PRECISION DEFAULT -1,
    F_GH_BIS                      DOUBLE PRECISION DEFAULT -1,
    F_GH_EINHEIT                  VARCHAR(15),
    F_RC                          VARCHAR(50),
    F_RC_BIS                      DOUBLE PRECISION DEFAULT -1,
    F_RC_VON                      DOUBLE PRECISION DEFAULT -1,
    F_RC_TIEFE                    VARCHAR(50),
    F_RC_TIEFE_VON                DOUBLE PRECISION DEFAULT -1,
    F_RC_TIEFE_BIS                DOUBLE PRECISION DEFAULT -1,
    F_RC_TIEFE_EINHEIT            VARCHAR(15),
    F_HAERTELAENGE                VARCHAR(50),
    F_HAERTELAENGE_VON            DOUBLE PRECISION DEFAULT -1,
    F_HAERTELAENGE_BIS            DOUBLE PRECISION DEFAULT -1,
    F_HAERTELAENGE_EINHEIT        VARCHAR(15),
    F_WEICHLAENGE                 VARCHAR(50),
    F_WEICHLAENGE_VON             DOUBLE PRECISION DEFAULT -1,
    F_WEICHLAENGE_BIS             DOUBLE PRECISION DEFAULT -1,
    F_WEICHLAENGE_EINHEIT         VARCHAR(15),
    F_HAFTUNGSKLASSE              INTEGER DEFAULT 0,
    F_KOMMENTAR                   VARCHAR(1000),
    F_FH                          VARCHAR(50),
    F_FH_VON                      DOUBLE PRECISION DEFAULT -1,
    F_FH_BIS                      DOUBLE PRECISION DEFAULT -1,
    F_FH_EINHEIT                  VARCHAR(15),
    F_SCHICHTDICKE                VARCHAR(50),
    F_SCHICHTDICKE_VON            DOUBLE PRECISION DEFAULT -1,
    F_SCHICHTDICKE_BIS            DOUBLE PRECISION DEFAULT -1,
    F_SCHICHTDICKE_EINHEIT        VARCHAR(15)
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE T_ERGEBNISDATEN ADD CONSTRAINT PK_ED PRIMARY KEY (ID_ERGEBNISDATEN);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE DESCENDING INDEX IND_ERGEBNISDATEN_ID ON T_ERGEBNISDATEN (ID_ERGEBNISDATEN);


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON T_ERGEBNISDATEN TO DBUSER WITH GRANT OPTION;


/******************************************************************************/
/***               Generated by IBExpert 04.07.2006 09:24:29                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE T_PRUEFERGEBNIS_APOS (
    F_ID_ERGEBNISDATEN     INTEGER NOT NULL,
    F_ID_APOS              INTEGER NOT NULL,
    F_ID_ANLAGE            INTEGER NOT NULL,
    F_ID_ERGEBNISDATEN_MS  INTEGER DEFAULT 0 NOT NULL,
    F_KOMMENTAR            VARCHAR(1000),
    F_TEILNR               VARCHAR(100),
    F_AUFNAHME_AUF_PZ      INTEGER,
    F_ID_MA_ACT            INTEGER,
    F_ERFASSUNG            TIMESTAMP,
    F_ZWISCHENPRUEFUNG     INTEGER,
    F_TPIO                 INTEGER,
    F_BIEGEWINKEL          DOUBLE PRECISION,
    F_BRUCHDREHMOMENT      DOUBLE PRECISION,
    F_RUNDLAUF             DOUBLE PRECISION,
    F_ANZAHL_OK            INTEGER DEFAULT -1,
    F_ANZAHL_NOK           INTEGER DEFAULT -1,
    F_ANZAHL_ZERSTOERT     INTEGER DEFAULT -1
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE T_PRUEFERGEBNIS_APOS ADD CONSTRAINT PK_PEA PRIMARY KEY (F_ID_ERGEBNISDATEN);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE T_PRUEFERGEBNIS_APOS ADD CONSTRAINT FK_PEA_APOS FOREIGN KEY (F_ID_APOS) REFERENCES T_APOS (ID_APOS) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_APOS ADD CONSTRAINT FK_PEA_ED FOREIGN KEY (F_ID_ERGEBNISDATEN) REFERENCES T_ERGEBNISDATEN (ID_ERGEBNISDATEN) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_APOS ADD CONSTRAINT FK_PEA_MIT FOREIGN KEY (F_ID_MA_ACT) REFERENCES T_MITARBEITER (ID_MITARBEITER) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_APOS ADD CONSTRAINT PFK_PEA_ANL FOREIGN KEY (F_ID_ANLAGE) REFERENCES T_ANLAGE (ID_ANLAGE) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_APOS ADD CONSTRAINT PFK_PEA_MS FOREIGN KEY (F_ID_ERGEBNISDATEN_MS) REFERENCES T_MESSSTELLE (F_ID_ERGEBNISDATEN) ON DELETE SET DEFAULT ON UPDATE NO ACTION;


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON T_PRUEFERGEBNIS_APOS TO DBUSER WITH GRANT OPTION;

/******************************************************************************/
/***               Generated by IBExpert 04.07.2006 09:24:41                ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE T_PRUEFERGEBNIS_WBHCHARGE (
    F_ID_ERGEBNISDATEN  INTEGER NOT NULL,
    F_ID_CHARGE         INTEGER NOT NULL,
    F_ID_ANLAGE         INTEGER NOT NULL,
    F_ID_VORSCHRIFT     INTEGER NOT NULL,
    F_ID_WERKSTOFF      INTEGER NOT NULL,
    F_KOMMENTAR         VARCHAR(1000),
    F_TEILNR            VARCHAR(100),
    F_ID_MA_ACT         INTEGER,
    F_ERFASSUNG         TIMESTAMP,
    F_TPIO              INTEGER,
    F_BIEGEWINKEL       DOUBLE PRECISION,
    F_BRUCHDREHMOMENT   DOUBLE PRECISION,
    F_RUNDLAUF          DOUBLE PRECISION,
    F_ANZAHL_OK         INTEGER DEFAULT -1,
    F_ANZAHL_NOK        INTEGER DEFAULT -1,
    F_ANZAHL_ZERSTOERT  INTEGER DEFAULT -1
);




/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT PK_PEWC PRIMARY KEY (F_ID_ERGEBNISDATEN);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT FK_PEWC_ANL FOREIGN KEY (F_ID_ANLAGE) REFERENCES T_ANLAGE (ID_ANLAGE) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT FK_PEWC_CHARGE FOREIGN KEY (F_ID_CHARGE) REFERENCES T_CHARGE (ID_CHARGE) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT FK_PEWC_ED FOREIGN KEY (F_ID_ERGEBNISDATEN) REFERENCES T_ERGEBNISDATEN (ID_ERGEBNISDATEN) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT FK_PEWC_MIT FOREIGN KEY (F_ID_MA_ACT) REFERENCES T_MITARBEITER (ID_MITARBEITER) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT FP_PEWC_VOR FOREIGN KEY (F_ID_VORSCHRIFT) REFERENCES T_BEHVORSCHRIFT (ID_BEHVORSCHRIFT) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE T_PRUEFERGEBNIS_WBHCHARGE ADD CONSTRAINT FP_PEWC_WERK FOREIGN KEY (F_ID_WERKSTOFF) REFERENCES T_WERKSTOFF (ID_WERKSTOFF) ON DELETE CASCADE ON UPDATE NO ACTION;


/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/


/* Privileges of users */
GRANT ALL ON T_PRUEFERGEBNIS_WBHCHARGE TO DBUSER WITH GRANT OPTION;
