/******************************************************************************/
/****       Generated by IBExpert 2011.01.11 12/15/2011 11:06:03 AM        ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES UTF8;

SET CLIENTLIB 'C:\Program Files\Fishbowl2012.2\database\odbc\fbclient32.dll';

CREATE DATABASE 'localhost:C:\Local\testcte.fdb'
USER 'SYSDBA' PASSWORD 'habcabom'
PAGE_SIZE 16384
DEFAULT CHARACTER SET UTF8 COLLATION UTF8;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_CONTACTS_ID;
SET GENERATOR GEN_CONTACTS_ID TO 15;

CREATE GENERATOR GEN_CUSTOMERS_ID;
SET GENERATOR GEN_CUSTOMERS_ID TO 17;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE CONTACTS (
    ID        INTEGER NOT NULL,
    AGE       INTEGER,
    NAME      VARCHAR(255),
    CUSTOMER  INTEGER NOT NULL
);

CREATE TABLE CUSTOMERS (
    ID        INTEGER NOT NULL,
    NAME      VARCHAR(255),
    PARENTID  INTEGER
);

INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (1, 'Dent', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (2, 'Troprosys USA', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (3, 'Gralpingro GmbH', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (4, 'Systed', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (5, 'Tian', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (6, 'Logy Asia', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (7, 'Nalf Devices', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (8, 'Coak', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (9, 'BOO Consulting', NULL);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (10, 'Gral-Berlin', 3);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (11, 'Gral-Hamburg', 3);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (12, 'Gral-Munich', 3);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (13, 'Gral-Cologne', 3);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (14, 'Logy-Japan', 6);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (15, 'Logy-Tokyo', 14);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (16, 'Logy-Kyoto', 14);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (17, 'Logy-Tokyo-West', 15);
INSERT INTO CUSTOMERS (ID, NAME, PARENTID) VALUES (18, 'Logy-Tokyo-East', 15);

COMMIT WORK;

INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (1, 21, 'ABC', 11);
INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (2, 82, 'Paige Chen', 8);
INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (10, 23, 'Whatever', 17);
INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (11, 22, 'Someone', 17);
INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (12, 23, 'manager', 17);
INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (13, 44, 'manager', 17);
INSERT INTO CONTACTS (ID, AGE, NAME, CUSTOMER) VALUES (15, 55, 'CEO', 9);

COMMIT WORK;



/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CONTACTS ADD CONSTRAINT PK_CONTACTS PRIMARY KEY (ID);
ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (ID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE CONTACTS ADD CONSTRAINT FK_CONTACTS_1 FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS (ID);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: CONTACTS_BI */
CREATE TRIGGER CONTACTS_BI FOR CONTACTS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.id IS NULL) THEN
    NEW.id = GEN_ID(gen_contacts_id,1);
END
^

/* Trigger: CUSTOMERS_BI */
CREATE TRIGGER CUSTOMERS_BI FOR CUSTOMERS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.id IS NULL) THEN
    NEW.id = GEN_ID(gen_customers_id,1);
END
^

SET TERM ; ^



/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/


/* Privileges of users */
GRANT SELECT ON RDB$FORMATS TO PUBLIC;
GRANT SELECT ON RDB$PAGES TO PUBLIC;
GRANT SELECT ON RDB$ROLES TO PUBLIC;
