/******************************************************************************/
/****         Generated by IBExpert 2007.07.17 04/09/2007 21:50:05         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

SET CLIENTLIB 'C:\Arquivos de programas\Firebird\Firebird_2_0\bin\fbclient.dll';

CREATE DATABASE 'LOCALHOST:C:\db\dbwaiter.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE DUAL (
    DUMMY  CHAR(1)
);

