SET TERM ^ ;

CREATE OR ALTER PROCEDURE P1 (
    ID_DOC INTEGER,
    I_CNT INTEGER)
RETURNS (
    I1 INTEGER)
AS
BEGIN
  EXIT;
END
^

CREATE OR ALTER PROCEDURE P0 (I_CNT INTEGER)
RETURNS (
    I1 INTEGER,
    DB_EXECUTE_TIME DOUBLE PRECISION)
AS
BEGIN
  EXIT;
END
^
COMMIT ^

RECREATE GLOBAL TEMPORARY TABLE TTMP (
    IDDOC                  INTEGER NOT NULL,
    IDMNF2_CONFIG_ITEM_LL  INTEGER NOT NULL,
    IDMNF2_CONFIG_ITEM     INTEGER NOT NULL,
    DTSTART                DATE,
    DTEND                  DATE,
    DBFACT_M3              DOUBLE PRECISION,
    DBPLAN_M3              DOUBLE PRECISION,
    IFACT_PIECES           INTEGER,
    IPLAN_PIECES           INTEGER,
    CKRATNOST              VARCHAR(100),
    CTHICKNESS             VARCHAR(100),
    DBFACT_M3_LL           DOUBLE PRECISION,
    IFACT_PIECES_LL        INTEGER,
    DBPLAN_PERF_M3H_NORMA  DOUBLE PRECISION
) ON COMMIT DELETE ROWS^


CREATE OR ALTER PROCEDURE P1 (
    ID_DOC INTEGER,
    I_CNT INTEGER)
RETURNS (
    I1 INTEGER)
AS
BEGIN
  DELETE FROM TTMP WHERE IDDOC = :ID_DOC;
  I1 = 0;
  WHILE(I1 < I_CNT) DO
  BEGIN
    INSERT INTO TTMP (IDDOC, IDMNF2_CONFIG_ITEM_LL, IDMNF2_CONFIG_ITEM, DTSTART, DTEND, DBFACT_M3, DBPLAN_M3, IFACT_PIECES,
                      IPLAN_PIECES, CKRATNOST, CTHICKNESS, DBFACT_M3_LL, IFACT_PIECES_LL, DBPLAN_PERF_M3H_NORMA)
    VALUES (:ID_DOC, MOD(:I1, 4), MOD(:I1, 12), 'NOW', CAST('NOW' AS TIMESTAMP)+1e0/24/60, 0, 0, 0,
            0, '1.3', '1.55', 0, 0, 0);

    I1 = I1 + 1;
  END
  SUSPEND;
END
^

CREATE OR ALTER PROCEDURE P0 (I_CNT INTEGER)
RETURNS (
    I1 INTEGER,
    DB_EXECUTE_TIME DOUBLE PRECISION)
AS
DECLARE DT TIMESTAMP;
DECLARE ITMP INTEGER;
BEGIN
  I1 = 0;
  WHILE(I1 < I_CNT) DO
  BEGIN
    DELETE FROM TTMP WHERE 0=0;
    SELECT COUNT(*) FROM TTMP INTO :ITMP;

    DT = CAST('NOW' AS TIMESTAMP);
    FOR SELECT I1 FROM P1(:I1, 30000) INTO :ITMP DO LEAVE;
    DB_EXECUTE_TIME = (CAST('NOW' AS TIMESTAMP) - DT) * 24*60*60*1000;

    SUSPEND;
    I1 = I1 + 1;
  END
END
^

SET TERM ; ^


COMMIT;

SELECT * FROM P0(25);
SELECT * FROM P0(25);

COMMIT;
EXIT;


